Django_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('comments/',include('comments.urls')),
    path('',include('blog.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
            settings.STATIC_URL,
            document_root=settings.STATIC_ROOT,
            ) + static(
                    settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT,
                    )

blog/urls.py
from django.urls import path,re_path
from . import views

app_name = 'myblog'

urlpatterns = [
    path('', views.index,name = 'index'),
    re_path('^detail/(?P<pk>\d+)/$',views.detail.as_view(),name = 'detail'),
    path('blog',views.blog.as_view(),name = 'bloglist'),
]

comments/urls.py
from django.urls import path,re_path
from . import views

app_name = 'comments'

urlpatterns = [
    re_path(r'comment/post/(?P<post_pk>\d+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import strip_tags
from ckeditor.fields import RichTextField

from user.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=60,verbose_name='文章标题')
    titleimg = models.ImageField(upload_to='titleimg/%Y/%m/%d/',null=True,blank=True,verbose_name='标题图片')
    body = RichTextField(verbose_name='正文内容')

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    excerpt = models.CharField(max_length=300,null=True,blank=True)
    category = models.ForeignKey('Category',None,verbose_name='文章分类')
    tags = models.ManyToManyField('Tag',verbose_name='文章标签')
    user = models.ForeignKey(User, null=True,on_delete=models.SET_NULL)
    views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('myblog:detail',kwargs={'pk':self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self,*args,**kwargs):
        if not self.excerpt:
            self.excerpt = strip_tags(self.body)[:108]
        super(Post, self).save(*args,**kwargs)

blog/views.py
from django.shortcuts import render
from django.utils.text import slugify
from django.views.generic import ListView,DetailView

from comments.forms import CommentForm
from .models import Post
import utils
# Create your views here.


def index(request):
    return render(request,'index.html', context={'my_page': 'index'})

class detail(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self,request,*args,**kwargs):
        response = super().get(request,*args,**kwargs)
        self.object.increase_views()
        return response


    def get_context_data(self, **kwargs):
        # 调用父类的get_context_data，获取原始的context对象
        context = super().get_context_data(**kwargs)
        post = self.object
        # 添加额外的上下文对象
        form = CommentForm()
        comment_list = post.comment_set.all()
        # 更新context
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


class blog(ListView):
    model = Post
    template_name = 'blog/blog.html'
    context_object_name = 'post_list'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(blog, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        start,end = utils.custompaginator(paginator.num_pages,page.number, 10)
        context.update(
            {
                'page_range' : range(start,end + 1),
                'my_page':'blog'
            }
        )
        return context

templates/blog/blog.html
{% extends 'base.html' %}

{% block container %}

        <div class="gallery-head">
            <h5>文章列表</h5>
            <p>在这里,你可以任性地创作,一篇短文、一张照片、一首诗、一幅画……我们相信,每个人都是生活中的艺术家,有着无穷的创造力。</p>
        </div>
    <div class="blog">
    {% for post in post_list %}
					<div class="blog-grid">
                        {% if post.titleimg %}
                        <div class="col-xs-4 blog-grid-left">
							<a href="{{ post.get_absolute_url }}"><img src="{{ post.titleimg.url }}" alt=" " class="img-responsive"></a>
						</div>
						<div class="col-xs-8 blog-grid-right">
                            {% else %}
                            <div class="col-xs-12 blog-grid-right">
                        {% endif %}

							<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
							<p>{{ post.excerpt }}</p>
							<a href="{{ post.get_absolute_url }}"><span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span></a>
						</div>
						<div class="clearfix"> </div>
					</div>
    {% endfor %}
    </div>

        {% if is_paginated %}
        <div class="pagination-simple">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}

            {% for i in page_range %}
                {% if page_obj.number == i %}
                    <a style="color:red;font-size:26px;padding: 5px" href="?page={{ i }}">{{ i }}</a>
                {% else %}
                    <a style="padding: 5px" href="?page={{ i }}">{{ i }}</a>
                {% endif %}

            {% endfor %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block container %}

				<!-- single -->
					<div class="single">
						<h3>{{ post.title }}</h3>
                        <div class="single-left">
							<p>阅读量：<span>{{ post.views }}</span></p>
						</div>
                        <div class="clearfix"> </div>
						<p class="tortor">
                            {{ post.body | safe }}</p>
						<div class="tags-cate">
							<div class="cat-grid">
								<h4><span>文</span>章类别</h4>
								<ul>
                                    <li><a href="#">{{ post.category }}</a></li>
								</ul>
							</div>
							<div class="cat-grid">
								<h4><span>发</span>布时间</h4>
								<ul>
                                    <li><a href="#">{{ post.created_time }}</a></li>
								</ul>
							</div>
							<div class="cat-grid">
								<h4><span>标</span>签</h4>

								<div class="top-social-icons">
                                    {% for tag in post.tags.all %}
										<a href="#">{{ tag.name }}</a>
                                        {% if forloop.counter|divisibleby:3 %}
                                            <div class="clearfix"> </div>
                                        {% endif %}
                                    {% endfor %}
								</div>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="three-com">
							<h3>{{ comment_list | length }} 条<label>关于这篇文章的评论</label></h3>
                            {% for comment in comment_list %}
							<div class="tom-grid humour">
								<div class="tom">
									<img src="{{ comment.author.icon.url }}" alt=" ">
								</div>
								<div class="tom-right">
									<div class="Hardy">
										<h4><a href="#">{{ comment.author.nickname }}</a></h4>
										<p><label>{{ comment.created_time }}</label></p>
									</div>
									<div class="clearfix"> </div>
									<p class="lorem">{{ comment.text }}</p>
								</div>
								<div class="clearfix"> </div>
							</div>
                            {% endfor %}
						</div>
						<div class="leave-comment">
							<h4>留下您的评论</h4>
							<p>这是一种很好的方式，来参与我的的讨论吧。</p>
							<form action="{% url 'comments:post_comment' post.pk %}" method="post" >
                                {% csrf_token %}
{#								<label for="{{ form.text.id_for_label }}">评论：</label>#}
                                {{ form.text }}
                                {{ form.text.errors }}
								<input type="submit" value="发表评论">
								<div class="clearfix"> </div>
							</form>
						</div>
					</div>
				<!-- //single -->

{% endblock %}