Django_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('comments/',include('comments.urls')),
    path('',include('blog.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
            settings.STATIC_URL,
            document_root=settings.STATIC_ROOT,
            ) + static(
                    settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT,
                    )

blog/urls.py
from django.urls import path,re_path
from . import views

app_name = 'myblog'

urlpatterns = [
    path('', views.index,name = 'index'),
    re_path('^detail/(?P<pk>\d+)/$',views.detail.as_view(),name = 'detail'),
    path('blog',views.blog.as_view(),name = 'bloglist'),
]

user/urls.py
from django.urls import path, re_path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.register_user,name='register'),
    path('index/',views.index,name='index'),
    path('pubication',views.pubilcation,name='publication'),
    path('pubication_done',views.pubication_done,name='publication_done'),
    path('post_manage',views.post_manage,name='post_manage'),
    re_path('^post_delete/(?P<post_pk>\d+)/$',views.post_delete,name='post_delete')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>python博客</title>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Great Taste Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link rel="shortcut icon" href="{% static 'images/logo.jpg' %}">
    {% block css %}{% endblock %}
<!-- js -->
<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<!-- //js -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Comfortaa:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>

<!-- banner-body -->
	<div class="banner-body">
		<div class="container">
			<div class="banner-body-content">
			<div class="col-xs-3 banner-body-left">
				<div class="logo">
					<h1><a href="#">Python<span>博客</span></a></h1>
				</div>
				<div class="top-nav">
					<nav class="navbar navbar-default">
						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header">
						  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						  </button>
						</div>

						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
							<nav class="stroke">
								<ul class="nav navbar-nav">
                                    {% if my_page == 'index' %}
                                        <li class="active"><a href="{% url 'myblog:index' %}"><i class="home"></i>主页</a></li>
                                        {% else %}
                                        <li><a href="{% url 'myblog:index' %}" class="hvr-underline-from-left"><i class="home1"></i>主页</a></li>
                                    {% endif %}

									<li><a href="#" class="hvr-underline-from-left"><i class="picture1"></i>美图鉴赏</a></li>

                                    {% if my_page == 'blog' %}
                                        <li class="active"><a href="{% url 'myblog:bloglist' %}"><i class="edit"></i>文章列表</a></li>
                                    {% else %}
                                        <li><a href="{% url 'myblog:bloglist' %}" class="hvr-underline-from-left"><i class="edit1"></i>文章列表</a></li>
                                    {% endif %}
                                    {% if user.is_authenticated %}
									<li><a href="{% url 'users:index' %}" class="hvr-underline-from-left"><i class="text-size1"></i>个人信息管理</a></li>
                                    {% else %}
                                        <li><a href="{% url 'login' %}" class="hvr-underline-from-left"><i class="text-size1"></i>登录/注册</a></li>
                                    {% endif %}
									<li><a href="#" class="hvr-underline-from-left"><i class="envelope1"></i>联系我</a></li>
								</ul>
							</nav>
						</div>
						<!-- /.navbar-collapse -->
					</nav>
				</div>
				<div class="latest-news">
					<h2>我的资料</h2>
					<div class="panel-group">
					</div>
                    {% if user.is_authenticated %}
                        <img style="height: 170px;width: 170px;border: orange solid 2px" src="{{ user.icon.url }}" alt="">
                        <p style="color: black;font-size: 18px">昵称：<span>{{ user.nickname }}</span></p>
                        <p style="color: black;font-size: 18px">邮箱：<span style="font-size: 12px">{{ user.email }}</span></p>
                        <div style="margin-top: 20px" class="join">
						<a href="{% url 'logout' %}">退出登录</a>
					</div>
                        {% else %}
                        <div class="join">
						<a href="{% url 'login' %}">请先登录</a>
					</div>
                    {% endif %}

					<h3>Python之禅</h3>
                    <p>优美胜于丑陋，明了胜于晦涩，</p>
                    <p>简洁胜于复杂，复杂胜于凌乱，</p>
                    <p>扁平胜于嵌套，间隔胜于紧凑，</p>
                    <p>可读性很重要，即便假借特例的实用性之名，也不可违背这些规则......</p>
				</div>
			</div>

			<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>

			<div class="col-xs-9 banner-body-right">
                {% block container %}{% endblock %}
			</div>
			<div class="clearfix"> </div>
			<div class="footer">
				<div class="footer-left">
					<ul>
						<li><a href="#">隐私政策</a>|</li>
						<li><a href="#">使用条款</a>|</li>
						<li><a href="#">与我联系</a></li>
					</ul>
					<p>Copyright &copy; 2016.hahaha108 All rights reserved.</p>
				</div>
				<div class="footer-right">
					<ul class="social-nav model-3">
						<li><a href="#" class="icon icon-border facebook"></a></li>
						<li><a href="#" class="icon icon-border twitter"></a></li>
						 <li><a href="#" class="icon icon-border googleplus"></a></li>
						 <li><a href="#" class="icon icon-border github"></a></li>
						 <li><a href="#" class="icon icon-border rss"></a></li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		</div>
	</div>
<!-- //banner-body -->
<!-- for bootstrap working -->
	<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- //for bootstrap working -->
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
    				<div class="wmuSlider example1">
					<div class="wmuSliderWrapper">
						<article style="position: absolute; width: 100%; opacity: 0;">
							<div class="banner-wrap">
								<div class="banner">
								</div>
							</div>
						</article>
						<article style="position: absolute; width: 100%; opacity: 0;">
							<div class="banner-wrap">
								<div class="banner1">
								</div>
							</div>
						</article>
						<article style="position: absolute; width: 100%; opacity: 0;">
							<div class="banner-wrap">
								<div class="banner2">
								</div>
							</div>
						</article>
					</div>
				</div>
					<script src="{% static 'js/jquery.wmuSlider.js' %}"></script>
					  <script>
						$('.example1').wmuSlider();
					 </script>
				<div class="banner-bottom">
					<div class="col-md-4 banner-left">
						<div class="col-xs-3 banner-left1">
							<div class="banner-left11">
								<span> </span>
							</div>
						</div>
						<div class="col-xs-9 banner-right1">
							<h3>怎么定义「想清楚了」？</h3>
						</div>
						<div class="clearfix"> </div>
						<p>“想清楚了”就是以后出了什么问题你只能找个没人的地方抽自己，再也不能抱怨别人了。</p>
					</div>
					<div class="col-md-4 banner-left">
						<div class="col-xs-3 banner-left1">
							<div class="banner-left11">
								<span> </span>
							</div>
						</div>
						<div class="col-xs-9 banner-right1">
							<h3>30 岁才开始学习编程靠谱吗？</h3>
						</div>
						<div class="clearfix"> </div>
						<p>种一棵树最好的时间是十年前，其次是现在。————CaunDerre</p>
					</div>
					<div class="col-md-4 banner-left">
						<div class="col-xs-3 banner-left1">
							<div class="banner-left11">
								<span> </span>
							</div>
						</div>
						<div class="col-xs-9 banner-right1">
							<h3>如何成为有想法的人？</h3>
						</div>
						<div class="clearfix"> </div>
						<p>你们有没有发现，很有想法的人往往“厚脸皮”，有想法的人太多了，敢说出来的人太少了。</p>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="msg-text">
					<div class="col-xs-2 msg-text-left">
						<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
					</div>
					<div class="col-xs-10 msg-text-right">
						<p>有的时候“慢工出细活”，再进一步讲这就是我们干工作中常说的“脑勤”，再干一件事情之前先清楚再干。很多时候我们盲干，费时费力效果不好，其实比起行动懒惰的更可怕的是思维上的懒惰。</p>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="msg-text-bottom">
					<div class="col-md-4 msg-text-bottom-left">
						<figure class="effect-winston">
							<a href="#"><img src="{% static 'images/4.jpg' %}" alt=" " class="img-responsive" />
							<figcaption>

							</figcaption>
							</a>
						</figure>

						<h3><a href="single.html">挤时间,好书需要读三遍！</a></h3>
						<p>时间就像海绵里的水，挤挤总会有的；时间就像美女的胸，挤挤都会有的！要想真正掌握一本书的核心内容，需要读三遍。</p>
					</div>
					<div class="col-md-4 msg-text-bottom-left">
						<figure class="effect-winston">
							<a href="#"><img src="{% static 'images/5.jpg' %}" alt=" " class="img-responsive" />
							<figcaption>

							</figcaption>
							</a>
						</figure>
						<h3><a href="#">碎片化时间系统化学习！</a></h3>
						<p>将碎片化的时间用来系统的学习某项知识或者技术，例如如果你想真正掌握微服务，就需要系统的学习，最方便的方式就是买几本微服务的书去啃！</p>
					</div>
					<div class="col-md-4 msg-text-bottom-left">
						<figure class="effect-winston">
							<a href="#"><img src="{% static 'images/6.jpg' %}" alt=" " class="img-responsive" />
							<figcaption>

							</figcaption>
							</a>
						</figure>
						<h3><a href="#">不管记不记得住，坚持看！</a></h3>
						<p>对于一项新知识或者新技能，一般情况下你坚持看 3~5 本相关的书，就会发现整个知识或者技能体系已经基本涵盖完毕，同样的内容会反复的在不同的书中出现，越看到后面，看书的速度越快。</p>
					</div>
					<div class="clearfix"> </div>
				</div>
{% endblock %}