Django_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('comments/',include('comments.urls')),
    path('',include('blog.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
            settings.STATIC_URL,
            document_root=settings.STATIC_ROOT,
            ) + static(
                    settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT,
                    )

blog/urls.py
from django.urls import path,re_path
from . import views

app_name = 'myblog'

urlpatterns = [
    path('', views.index,name = 'index'),
    re_path('^detail/(?P<pk>\d+)/$',views.detail.as_view(),name = 'detail'),
    path('blog',views.blog.as_view(),name = 'bloglist'),
]

user/urls.py
from django.urls import path, re_path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.register_user,name='register'),
    path('index/',views.index,name='index'),
    path('pubication',views.pubilcation,name='publication'),
    path('pubication_done',views.pubication_done,name='publication_done'),
    path('post_manage',views.post_manage,name='post_manage'),
    re_path('^post_delete/(?P<post_pk>\d+)/$',views.post_delete,name='post_delete')
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import strip_tags
from ckeditor.fields import RichTextField

from user.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=60,verbose_name='文章标题')
    titleimg = models.ImageField(upload_to='titleimg/%Y/%m/%d/',null=True,blank=True,verbose_name='标题图片')
    body = RichTextField(verbose_name='正文内容')

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    excerpt = models.CharField(max_length=300,null=True,blank=True)
    category = models.ForeignKey('Category',None,verbose_name='文章分类')
    tags = models.ManyToManyField('Tag',verbose_name='文章标签')
    user = models.ForeignKey(User, null=True,on_delete=models.SET_NULL)
    views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('myblog:detail',kwargs={'pk':self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self,*args,**kwargs):
        if not self.excerpt:
            self.excerpt = strip_tags(self.body)[:108]
        super(Post, self).save(*args,**kwargs)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    nickname = models.CharField(
        max_length=128,null=False,blank=False,unique=True,verbose_name='昵称'
    )
    icon = models.ImageField(upload_to='avatar/%Y/%m/%d/', default='default.jpg', null=True,blank=True, verbose_name='头像')

    class Meta(AbstractUser.Meta):
        pass

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms
from blog.models import Post


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'nickname', 'icon')


class PubilcationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','titleimg','body','category','tags']

# class PubilcationForm(forms.Form):
    # title = forms.CharField(label='标题',max_length=100)
    # body = RichTextFormField(label='正文')

user/views.py
import datetime
import logging

import os
import random
import string
import threading

from django.conf import settings
from django.shortcuts import render, redirect
from django.core.cache import cache

from blog.models import Post
from . import verify_code
from .forms import RegisterForm
from django.urls import reverse
from .forms import PubilcationForm
from .models import User
# Create your views here.

logger = logging.getLogger("django")

def register_user(request):
    # 生成验证码
    err_msg = None
    today_str = datetime.date.today().strftime("%Y%m%d")
    verify_code_img_path = os.path.join(settings.VERIFICATION_CODE_IMGS_DIR,today_str)
    if not  os.path.isdir(verify_code_img_path):
        os.makedirs(verify_code_img_path,exist_ok=True)
    random_filename = "".join(random.sample(string.ascii_lowercase,5))
    random_code = verify_code.gene_code(verify_code_img_path,random_filename)
    img_path = 'verify_code/'+ today_str + '/' + random_filename + '.png'
    # 验证码写入缓存字典中，并设置60秒过期时间
    cache.set(random_filename,random_code,60)
    print(os.path.join(verify_code_img_path,random_filename+'.png'))
    threading.Thread(target=verify_code.del_img,args=(os.path.join(verify_code_img_path,random_filename+'.png'),)).start()

    # 获取next的值
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    # 判断提交方法是否是post
    if request.method == 'POST':
        _verify_code = request.POST.get('verify_code')
        _verify_code_key = request.POST.get('verify_code_key')

        if cache.get(_verify_code_key) == _verify_code:

            # 接收post中的数据，并以此数据实例化modelform
            form = RegisterForm(request.POST, request.FILES)

            # 判断数据是否合法有效。
            if form.is_valid():
                # 数据有效，保存。
                form.save()

                # 判断是否需要跳转到之前的页面
                if redirect_to:
                    return redirect(redirect_to)
                else:
                    # 跳转到登录。
                    return redirect(reverse('login'))
        else:
            form = RegisterForm(request.POST, request.FILES)
            err_msg = '验证码输入错误'
    else:
        form = RegisterForm()
    return render(request, 'user/register.html', {'form':form,'next':redirect_to,'img_path':img_path,'filename':random_filename,'err_msg':err_msg})

def index(request):
    return render(request,'user/index.html')

def pubilcation(request):
    form = PubilcationForm()
    if request.method == 'POST':
        form = PubilcationForm(request.POST,request.FILES,)
        logger.warning('POST请求成功')
        current_user = request.user
        if form.is_valid():
            logger.warning('表单提交成功')
            post = form.save(commit=False)
            post.user = current_user
            post.save()
            form.save_m2m()
            return redirect(reverse('users:publication_done'))

    return render(request,'user/publication.html',{'form':form })

def pubication_done(request):
    return render(request,'user/pubication_done.html')

def post_manage(request):
    return render(request,'user/post_manage.html')

def post_delete(request,post_pk):
    pk = int(post_pk)
    logger.warning(pk)
    Post.objects.get(id = pk).delete()
    return redirect(reverse('users:post_manage'))

templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>用户信息管理</title>
    {% block css %}

    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'ui/themes/default/easyui.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'ui/themes/icon.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'ui/demo/demo.css' %}">
	<script type="text/javascript" src="{% static 'ui/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'ui/jquery.easyui.min.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'images/logo.jpg' %}">
    <link href="{%  static 'admin/bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{%  static 'admin/bower_components/metisMenu/dist/metisMenu.min.css' %}" rel="stylesheet">
    <link href="{%  static 'admin/dist/css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="{%  static 'admin/bower_components/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'admin/css/common.css' %}" type="text/css" rel="stylesheet">
    <style>
        .page-header{
            margin:12px;
        }
    </style>
</head>

<body>
<div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">下拉菜单</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'users:index' %}"><img src="{%  static 'images/co.png' %}" style="width:18px;height:18px;display:inline-block;">&nbsp;用户信息管理系统</a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> 管理员</a>
                    </li>
                                        <li class="divider"></li>
                    <li><a href="{% url 'myblog:index' %}"><i class="fa fa-sign-out fa-fw"></i> 返回博客</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> 退出登录</a>
                    </li>

                </ul>
            </li>
        </ul>
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="#"><i class="fa fa-tag" aria-hidden="true"></i> 个人信息管理<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'users:index' %}"><i class="fa fa-list" aria-hidden="true"></i> 我的信息</a>
                            </li>
                            <li>
                                <a href="{% url 'password_change' %}"><i class="fa fa-bolt" aria-hidden="true"></i> 修改密码</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-file-text" aria-hidden="true"></i> 文章管理<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'users:publication' %}"><i class="fa fa-filter" aria-hidden="true"></i> 发布新文章</a>
                            </li>
                             <li>
                                <a href="{% url 'users:post_manage' %}"><i class="fa fa-vimeo-square" aria-hidden="true"></i> 管理当前文章</a>
                            </li>

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}{% endblock %}

</div>

<script src="{%  static 'admin/bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{%  static 'admin/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{%  static 'admin/bower_components/metisMenu/dist/metisMenu.min.js' %}"></script>
<script src="{%  static 'admin/dist/js/sb-admin-2.js' %}"></script>

<script type="text/javascript" src="{%  static 'admin/ueditor/ueditor.config.js' %}"></script>
<script type="text/javascript" src="{%  static 'admin/ueditor/ueditor.all.js' %}"></script>
<script type="text/javascript" src="{%  static 'admin/ueditor/lang/zh-cn/zh-cn.js' %}"></script>


{% block js %}{% endblock %}
</body>

</html>

templates/user/index.html
{% extends "user/base.html" %}

{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">个人信息</h3>
            </div>
        </div>
         <img style="height: 270px;width: 270px;border: black solid 3px" src="{{ user.icon.url }}" alt="">
                        <p style="color: black;font-size: 22px;margin-top: 20px">昵称：<span>{{ user.nickname }}</span></p>
                        <p style="color: black;font-size: 22px;margin-top: 20px">邮箱：<span style="font-size: 17px">{{ user.email }}</span></p>
        </div>

    </div>

{% endblock %}

templates/user/post_manage.html
{% extends 'user/base.html' %}



{% block content %}
 <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">文章管理/文章列表</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        文章列表
                    </div>
                    <div class="panel-body">
                        <table class="table table-bordered">
                            <tr class="text-primary" style="font-weight:bold;">
                                <td style="width:10%">编号</td>
                                <td style="width:18%">标题</td>
                                <td style="width:18%">封面</td>
                                <td style="width:18%">标签</td>
                                <td style="width:18%">添加时间</td>
                                <td style="width:18%">操作</td>
                            </tr>
                            {% for v in user.post_set.all %}
                            <tr>
                                <td>{{ v.id }}</td>
                                <td>{{ v.title }}</td>
                                <td>
                                    {% if v.titleimg %}
                                    <img src="{{ v.titleimg.url }}" style="width:131px;height:83px;">
                                        {% else %}
                                        无封面
                                    {% endif %}

                                </td>
                                <td>{{ v.excerpt }}</td>
                                <td>{{ v.created_time }}</td>
                                <td>
                                    <a style="font-size: 14px" class="label label-warning" href="#"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> 编辑</a>&nbsp;
                                    <a style="font-size: 14px" class="label label-danger" href="#" data-toggle="modal" data-target="#myModal{{ v.id }}"><i class="fa fa-times" aria-hidden="true"></i> 删除</a>
                                    <div class="modal fade" id="myModal{{ v.id }}" tabindex="-1" role="dialog"
                                     aria-labelledby="myModalLabel">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close"><span aria-hidden="true">&times;</span>
                                                    </button>
                                                    <h4 class="modal-title" id="myModalLabel">删除操作</h4>
                                                </div>
                                                <div class="modal-body">
                                                    是否删除{{ v.id }}.{{ v.a_title }}这条记录？
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">撤销
                                                    </button>
                                                    <a class="btn btn-danger" href="{% url 'users:post_delete' v.id %}">确认</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/pubication_done.html
{% extends 'user/base.html' %}

{% block content %}
    <div id="page-wrapper">
        <div class="container">
            <div>
                <p>文章发布成功！</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/publication.html
{% extends 'user/base.html' %}

{% block js %}
<script type="text/javascript" src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
{% endblock %}

{% block css %}
    <style>
            #id_title{
            width: 580px;
        }
    label{
        font-size: 17px;margin-top: 13px;color: #0d6aad;
    }
    </style>
{% endblock %}

{% block content %}
    <div id="page-wrapper">
        <form class="form" action="{% url 'users:publication' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for lable in form %}
                <div>
                {{ lable.label_tag }}
                </div>
                <div>
                {{ lable }}
                </div>
                <div>
                {{ lable.errors }}
                </div>

            {% endfor %}
            <div>
                <button style="margin-top: 20px;margin-left: 90px;width: 120px" type="submit" class="btn btn-primary">
                    发表文章
                </button>
            </div>
        </form>
    </div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <style>
    ul li input{outline: none;border: 2px solid #E0BD62;font-size: 14px;margin:1em 0;width: 60%;margin-left: 5px}
    ul li label{width: 105px}
    #id_icon{border: 1px solid #FFFFFF;}
    #tb{margin-top: 30px}
    #zc{margin-top: 13px;background-color: #f0ad4e;border: 1px solid #FFFFFF;margin-bottom: 10px;width: 170px;height: 50px;font-size: 20px;}
    #yzm{outline: none;border: 2px solid #E0BD62;font-size: 14px;margin:1em 0;width: 30%;margin-left: 25px}
    </style>
{% endblock %}

{% block container %}
<h1>用户注册</h1>
                <form class="form" action="{% url 'users:register' %}" method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
                <ul id="tb">
                    {% for field in form %}
                        <li>
                        {{ field.label_tag }}
                        {{ field }}
                        </li>
                    {% endfor %}

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <img height="50px" src="{% static img_path %}">
                                </div>
                                <input id="yzm" type="text" name="verify_code" class="form-control" placeholder="请填写验证码">
                                <input type="hidden" name="verify_code_key" value="{{ filename }}" >
                            </div>
                    {% if err_msg %}
                        <p style="color: red">{{ err_msg }}</p>
                    {% endif %}

                  </ul>
                    <button id="zc" type="submit">注册</button>
                    <input type="hidden" name="next" value="{{ next }}"/>

                </form>

                <div class="flex-center top-gap text-small">
                    <a href="{% url 'login' %}">已有账号登录</a>
                </div>
{% endblock %}